### ISSUE TITLE
Chapter 1: Cartoonifier has stopped working

### ISSUE THREAD

**Issue by zshn25** [MasteringOpenCV/code#72]
First of all, great tutorial. The desktop app worked perfectly. When I ported it to Android, it shows the message `Unfortunately, Cartoonifier has stopped` on my Samsung Galaxy S5, which has Android 5. The LogCat of the same is below

```
03-16 17:22:48.654: D/ResourcesManager(10738): creating new AssetManager and set to /data/app/com.Cartoonifier-2/base.apk
03-16 17:22:48.694: I/CartoonifierApp(10738): Instantiated new class com.Cartoonifier.CartoonifierApp
03-16 17:22:48.744: I/CartoonifierApp(10738): onCreate
03-16 17:22:48.799: I/Cartoonifier::SurfaceView(10738): Instantiated new class com.Cartoonifier.CartoonifierView
03-16 17:22:48.814: D/Activity(10738): performCreate Call secproduct feature valuefalse
03-16 17:22:48.814: D/Activity(10738): performCreate Call debug elastic valuetrue
03-16 17:22:48.814: I/CartoonifierApp(10738): onResume
03-16 17:22:48.814: I/Cartoonifier::SurfaceView(10738): openCamera
03-16 17:22:48.814: I/Cartoonifier::SurfaceView(10738): releaseCamera
03-16 17:22:49.009: I/Cartoonifier::SurfaceView(10738): surfaceCreated
03-16 17:22:49.009: I/Cartoonifier::SurfaceView(10738): surfaceChanged(). Window size: 1920x1005
03-16 17:22:49.009: I/Cartoonifier::SurfaceView(10738): setupCamera(1920x1005)
03-16 17:22:49.009: I/Cartoonifier::SurfaceView(10738): Starting processing thread
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 1920x1080
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 1440x1080
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 1088x1088
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 1280x720
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 1056x704
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 960x720
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 720x720
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 720x480
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 640x480
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 352x288
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 320x240
03-16 17:22:49.014: I/Cartoonifier::SurfaceView(10738): Found Camera Resolution 176x144
03-16 17:22:49.024: I/Cartoonifier::SurfaceView(10738): Chosen Camera Preview Size: 1920x1080
03-16 17:22:49.069: E/BufferQueueProducer(10738): [unnamed-10738-0] dequeueBuffer: BufferQueue has been abandoned
03-16 17:22:49.069: E/BufferQueueProducer(10738): [unnamed-10738-0] dequeueBuffer: BufferQueue has been abandoned
03-16 17:22:49.069: E/BufferQueueProducer(10738): [unnamed-10738-0] dequeueBuffer: BufferQueue has been abandoned
03-16 17:22:49.069: E/BufferQueueProducer(10738): [unnamed-10738-0] dequeueBuffer: BufferQueue has been abandoned
03-16 17:22:49.069: E/BufferQueueProducer(10738): [unnamed-10738-0] dequeueBuffer: BufferQueue has been abandoned
03-16 17:22:50.249: D/AndroidRuntime(10738): Shutting down VM
03-16 17:22:50.254: E/AndroidRuntime(10738): FATAL EXCEPTION: main
03-16 17:22:50.254: E/AndroidRuntime(10738): Process: com.Cartoonifier, PID: 10738
03-16 17:22:50.254: E/AndroidRuntime(10738): java.lang.RuntimeException: startPreview failed
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.hardware.Camera.startPreview(Native Method)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at com.Cartoonifier.CartoonifierViewBase.setupCamera(CartoonifierViewBase.java:154)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at com.Cartoonifier.CartoonifierViewBase.surfaceChanged(CartoonifierViewBase.java:161)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.SurfaceView.updateWindow(SurfaceView.java:617)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:184)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:895)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2153)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.Choreographer.doCallbacks(Choreographer.java:590)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.Choreographer.doFrame(Choreographer.java:560)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.os.Handler.handleCallback(Handler.java:739)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.os.Handler.dispatchMessage(Handler.java:95)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.os.Looper.loop(Looper.java:145)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at android.app.ActivityThread.main(ActivityThread.java:5832)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at java.lang.reflect.Method.invoke(Native Method)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at java.lang.reflect.Method.invoke(Method.java:372)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
03-16 17:22:50.254: E/AndroidRuntime(10738):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by shervinemami** [comment]
Hi, the logcat says it failed in "startPreview", so I think it is a problem with initializing your camera. Have you tried getting the Android camera samples that come with OpenCV to work?

**Comment by zshn25** [comment]
Yes, they are working fine. Here's the LogCat

```
03-16 17:59:59.859: D/ResourcesManager(25978): creating new AssetManager and set to /data/app/org.opencv.samples.tutorial3-1/base.apk
03-16 17:59:59.889: I/OCVSample::Activity(25978): Instantiated new class org.opencv.samples.tutorial3.Tutorial3Activity
03-16 17:59:59.969: I/OCVSample::Activity(25978): called onCreate
03-16 18:00:00.009: D/CameraBridge(25978): Attr count: 4
03-16 18:00:00.014: D/Activity(25978): performCreate Call secproduct feature valuefalse
03-16 18:00:00.014: D/Activity(25978): performCreate Call debug elastic valuetrue
03-16 18:00:00.019: D/OpenCV/StaticHelper(25978): Trying to get library list
03-16 18:00:00.019: E/OpenCV/StaticHelper(25978): OpenCV error: Cannot load info library for OpenCV
03-16 18:00:00.019: D/OpenCV/StaticHelper(25978): Library list: ""
03-16 18:00:00.019: D/OpenCV/StaticHelper(25978): First attempt to load libs
03-16 18:00:00.019: D/OpenCV/StaticHelper(25978): Trying to init OpenCV libs
03-16 18:00:00.019: D/OpenCV/StaticHelper(25978): Trying to load library opencv_java3
03-16 18:00:00.019: D/OpenCV/StaticHelper(25978): Cannot load library "opencv_java3"
03-16 18:00:00.019: W/System.err(25978): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.opencv.samples.tutorial3-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libopencv_java3.so"
03-16 18:00:00.024: W/System.err(25978):    at java.lang.Runtime.loadLibrary(Runtime.java:366)
03-16 18:00:00.024: W/System.err(25978):    at java.lang.System.loadLibrary(System.java:989)
03-16 18:00:00.024: W/System.err(25978):    at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:64)
03-16 18:00:00.024: W/System.err(25978):    at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
03-16 18:00:00.024: W/System.err(25978):    at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
03-16 18:00:00.024: W/System.err(25978):    at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:72)
03-16 18:00:00.024: W/System.err(25978):    at org.opencv.samples.tutorial3.Tutorial3Activity.onResume(Tutorial3Activity.java:91)
03-16 18:00:00.024: W/System.err(25978):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
03-16 18:00:00.024: W/System.err(25978):    at android.app.Activity.performResume(Activity.java:6338)
03-16 18:00:00.024: W/System.err(25978):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3335)
03-16 18:00:00.024: W/System.err(25978):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3377)
03-16 18:00:00.024: W/System.err(25978):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2728)
03-16 18:00:00.024: W/System.err(25978):    at android.app.ActivityThread.access$900(ActivityThread.java:172)
03-16 18:00:00.024: W/System.err(25978):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
03-16 18:00:00.024: W/System.err(25978):    at android.os.Handler.dispatchMessage(Handler.java:102)
03-16 18:00:00.024: W/System.err(25978):    at android.os.Looper.loop(Looper.java:145)
03-16 18:00:00.024: W/System.err(25978):    at android.app.ActivityThread.main(ActivityThread.java:5832)
03-16 18:00:00.024: W/System.err(25978):    at java.lang.reflect.Method.invoke(Native Method)
03-16 18:00:00.024: W/System.err(25978):    at java.lang.reflect.Method.invoke(Method.java:372)
03-16 18:00:00.024: W/System.err(25978):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
03-16 18:00:00.024: W/System.err(25978):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
03-16 18:00:00.024: D/OpenCV/StaticHelper(25978): First attempt to load libs fails
03-16 18:00:00.024: D/OCVSample::Activity(25978): Internal OpenCV library not found. Using OpenCV Manager for initialization
03-16 18:00:00.354: D/CameraBridge(25978): call surfaceChanged event
03-16 18:00:00.354: D/CameraBridge(25978): call checkCurrentState
03-16 18:00:00.424: D/OpenCVManager/Helper(25978): Service connection created
03-16 18:00:00.444: D/OpenCVManager/Helper(25978): Trying to get library path
03-16 18:00:00.444: D/OpenCVManager/Helper(25978): Trying to get library list
03-16 18:00:00.444: D/OpenCVManager/Helper(25978): Library list: "libopencv_java3.so"
03-16 18:00:00.444: D/OpenCVManager/Helper(25978): First attempt to load libs
03-16 18:00:00.444: D/OpenCVManager/Helper(25978): Trying to init OpenCV libs
03-16 18:00:00.444: D/OpenCVManager/Helper(25978): Trying to load libs by dependency list
03-16 18:00:00.444: D/OpenCVManager/Helper(25978): Trying to load library /data/app/org.opencv.engine-1/lib/arm/libopencv_java3.so
03-16 18:00:00.514: D/OpenCVManager/Helper(25978): OpenCV libs init was ok!
03-16 18:00:00.514: D/OpenCVManager/Helper(25978): First attempt to load libs is OK
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   videoio: Removing WinRT API headers by default
03-16 18:00:00.519: I/OpenCVManager/Helper(25978): General configuration for OpenCV 3.0.0 =====================================
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Version control:               3.0.0-6-gc1f114b-dirty
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Platform:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Host:                        Linux 3.13.0-53-generic x86_64
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Target:                      Linux 1 armv7-a
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     CMake:                       2.8.12.2
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     CMake generator:             Ninja
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     CMake build tool:            /usr/bin/ninja
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Configuration:               Release
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   C/C++:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Built as dynamic libs?:      NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     C++ Compiler:                /usr/bin/ccache /home/maksim/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ (ver 4.8)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     C++ flags (Release):         -fexceptions -frtti -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     C++ flags (Debug):           -fexceptions -frtti -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -O0 -DDEBUG -D_DEBUG
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     C Compiler:                  /usr/bin/ccache /home/maksim/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     C flags (Release):           -fexceptions -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     C flags (Debug):             -fexceptions -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -O0 -DDEBUG -D_DEBUG
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Linker flags (Release):      -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now 
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Linker flags (Debug):        -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now 
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Precompiled headers:         NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Extra dependencies:          z dl m log
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     3rdparty dependencies:       libjpeg libwebp libpng libtiff libjasper IlmImf tbb
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   OpenCV modules:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     To be built:                 hal core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d java stitching videostab
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Disabled:                    world
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Disabled by dependency:      -
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python2 viz
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Android: 
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Android ABI:                 armeabi-v7a with NEON
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     STL type:                    gnustl_static
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Native API level:            android-8
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     SDK target:                  android-11
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Android NDK:                 /home/maksim/android-ndk-r10e (toolchain: arm-linux-androideabi-4.8)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     android tool:                /home/maksim/android-sdk-linux/tools/android (Android SDK Tools, revision 24.3.)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Google Play manager:         NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Android examples:            YES
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   GUI: 
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     GTK+:                        NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     GThread :                    NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     GtkGlExt:                    NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     OpenGL support:              NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     VTK support:                 NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Media I/O: 
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     ZLib:                        z (ver 1.2.3)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     JPEG:                        build (ver 90)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     WEBP:                        build (ver 0.3.1)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     PNG:                         build (ver 1.5.12)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     TIFF:                        build (ver 42 - 4.0.2)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     JPEG 2000:                   build (ver 1.900.1)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     OpenEXR:                     build (ver 1.7.1)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     GDAL:                        NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Video I/O:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Other third-party libraries:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use IPP:                     NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use Eigen:                   NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use TBB:                     YES (ver 4.1 interface 6102)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use OpenMP:                  NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use GCD                      NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use Concurrency              NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use C=:                      NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use pthreads for parallel for:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):                                  NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use Cuda:                    NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Use OpenCL:                  NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Python 2:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Python 3:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Interpreter:                 /usr/bin/python3.4 (ver 3.4)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Python (for build):            /usr/bin/python2.7
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Java:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     ant:                         /usr/bin/ant (ver 1.9.3)
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Java wrappers:               YES
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Java tests:                  YES
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Matlab:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     mex:                         NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Documentation:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Doxygen:                     NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     PlantUML:                    NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Tests and samples:
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Tests:                       YES
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     Performance tests:           NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):     C/C++ Examples:              NO
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   Install path:                  /home/maksim/workspace/android-pack/builds/o4a/install
03-16 18:00:00.519: I/OpenCVManager/Helper(25978):   cvconfig.h is in:              /home/maksim/workspace/android-pack/builds/o4a
03-16 18:00:00.519: I/OpenCVManager/Helper(25978): -----------------------------------------------------------------
03-16 18:00:00.519: D/OpenCVManager/Helper(25978): Init finished with status 0
03-16 18:00:00.519: D/OpenCVManager/Helper(25978): Unbind from service
03-16 18:00:00.524: D/OpenCVManager/Helper(25978): Calling using callback
03-16 18:00:00.524: I/OCVSample::Activity(25978): OpenCV loaded successfully
03-16 18:00:00.524: D/CameraBridge(25978): call checkCurrentState
03-16 18:00:00.524: D/CameraBridge(25978): call processExitState: 0
03-16 18:00:00.524: D/CameraBridge(25978): call processEnterState: 1
03-16 18:00:00.524: D/CameraBridge(25978): call onEnterStartedState
03-16 18:00:00.524: D/JavaCameraView(25978): Connecting to camera
03-16 18:00:00.524: D/JavaCameraView(25978): Initialize java camera
03-16 18:00:00.524: D/JavaCameraView(25978): Trying to open camera with old open()
03-16 18:00:00.609: D/JavaCameraView(25978): getSupportedPreviewSizes()
03-16 18:00:00.614: D/JavaCameraView(25978): Set preview size to 1920x1080
03-16 18:00:00.654: D/JavaCameraView(25978): startPreview
03-16 18:00:01.189: D/JavaCameraView(25978): Starting processing thread
03-16 18:00:01.189: I/Choreographer(25978): Skipped 46 frames!  The application may be doing too much work on its main thread.
03-16 18:00:01.194: I/Timeline(25978): Timeline: Activity_idle id: android.os.BinderProxy@3536bc2 time:20488533
03-16 18:00:01.639: D/JavaCameraView(25978): Preview Frame received. Frame size: 3110400
....
03-16 18:00:04.529: D/JavaCameraView(25978): Preview Frame received. Frame size: 3110400
03-16 18:00:04.549: D/CameraBridge(25978): call checkCurrentState
03-16 18:00:04.549: D/CameraBridge(25978): call processExitState: 1
03-16 18:00:04.549: D/JavaCameraView(25978): Disconnecting from camera
03-16 18:00:04.549: D/JavaCameraView(25978): Notify thread
03-16 18:00:04.549: D/JavaCameraView(25978): Wating for thread
03-16 18:00:04.569: D/CameraBridge(25978): mStretch value: 1.0
03-16 18:00:04.589: D/JavaCameraView(25978): Finish processing thread
03-16 18:00:04.834: D/CameraBridge(25978): call processEnterState: 0
03-16 18:00:05.054: D/CameraBridge(25978): call checkCurrentState
03-16 18:00:05.479: W/IInputConnectionWrapper(25978): showStatusIcon on inactive InputConnection
03-16 18:00:06.464: D/CameraBridge(25978): call checkCurrentState
```

**Comment by shervinemami** [comment]
Oh I see you're using OpenCV 3. I haven't updated the code to work with OpenCV 3 yet (it will happen within the next few months). So for now I guess you'll have to use OpenCV 2 or modify the code to use the same camera capture code that the new OpenCV 3 camera samples use, since it must have changed.

**Comment by zshn25** [comment]
Oh, that explains it. Thanks. Please update when you port the code to OpenCV 3.
